export { default as flipImage } from "./flip.js"
export { default as scaleImage } from "./scale.js"
export { default as tintImage } from "./tint.js"
export { default as makeCircle } from "./make-circle.js"
export { default as makeRectangle } from "./make-rectangle.js"
